server:
  port: 6060

spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/jpa_test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
